### ISSUE TITLE
Get Gmail to not group confirmation emails

### ISSUE THREAD

**Issue by RebeccaRGB** [harmonious-elements/concrescent#21]

**Comment by Tsaukpaetra** [comment]
It should be possible to mangle the subject line so it's unique, which will prevent gmail from grouping it.

**Comment by RebeccaRGB** [comment]
That's not how it works. There's a header that does it.

**Comment by Tsaukpaetra** [comment]
Yeah, there's an in-reply-to header, but we don't apply that upon sending.  When receiving a message for the first time that header isn't present so it falls back to the subject line.

I don't have any more evidence than research people did several years ago, but it can't hurt to try.

http://www.sensefulsolutions.com/2010/08/how-does-email-threading-work-in-gmail.html

**Comment by RebeccaRGB** [comment]
That's not how it works either. You do realize I work at Google and would therefore know more about how Gmail threads messages than random Internet "researchers", don't you? ;-)

**Comment by Tsaukpaetra** [comment]
Your employment details aren't known to me. :wink: for all I know you could be a manager at a winery. :stuck_out_tongue_closed_eyes:.
Actually, probably the one thing I do know bussiness wise is you made fonts. :+1:. 
Additionally, merely working at a company doesn't necessarily make you privy to information within of about that company's products. For example, I wouldn't expect a finance director to know how the company's flagship game product keeps track of player status (though admittedly it would be much easier to find out that by someone on the outside). ...
