### ISSUE TITLE
Unicode input gets mangled?

### ISSUE THREAD

**Issue by RebeccaRGB** [harmonious-elements/concrescent#22]
Panel application titled "We ♥ Sunset Shimmer" came out "We ? Sunset Shimmer". Editing the application did not fix the encoding issue.

**Comment by RebeccaRGB** [comment]
Fixed in revision 188. Also fixed panel application.

**Comment by fundamentals-fontdevelopment** [comment]
Undo this fix. Nobody wants any cringy emojis aside from you.
